/*
 * Copyright (c) 2014, Richard Lemon <richard@codelemon.com>
 *
 * This software is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
#include <string.h>

#define SPARSE_MAGICNUMBER 0x564d444b

typedef uint64_t SectorType;
typedef uint8_t Bool;
typedef struct  __attribute__((__packed__)) SparseExtentHeader {
	uint32_t magicNumber;
	uint32_t version;
	uint32_t flags;
	SectorType capacity;
	SectorType grainSize;
	SectorType descriptorOffset;
	SectorType descriptorSize;
	uint32_t numGTEsPerGT;
	SectorType rgdOffset;
	SectorType gdOffset;
	SectorType overHead;
	Bool uncleanShutdown;
	char singleEndLineChar;
	char nonEndLineChar;
	char doubleEndLineChar1;
	char doubleEndLineChar2;
	uint16_t compressAlgorithm;
	uint8_t pad[433];
} SparseExtentHeader;

void print_opts() {
	printf("This program exists because I lost my descriptor file for a VM but still had all of the sparse files.\n");
	printf("It reads the file header information and prints it in the format required for the descriptor file.\n\n\n");
	printf("vmdk <filename>\n");
	printf("     <filename> - A sparse file filename(e.g winxp-0001.vmdk)\n\n");
	printf("You need 2 bits of information to recreate the vmdk descriptor file, the disk geometry and the sparse file information.\n");
	printf("The disk geometry can be found in the vmware.log files in the form:\n");
	printf("\tGeo (83220/16/63)\n");
	printf("These become the following\n");
	printf("ddb.geometry.cylinders = \"83220\"\n");
	printf("ddb.geometry.heads = \"16\"\n");
	printf("ddb.geometry.sectors = \"63\"\n");
	printf("The sparse file information is generated by this program.\n");
	printf("e.g.\n$> for A in `ls *.vmdk`; do ~/vmdk $A; done\n\n");
	printf("The rest of the structure of the file can be created by copying another disk file.\n");
}

int main(int argc, char **argv) {
	SparseExtentHeader header_data;
	char* file_name = argv[1];
	int ret_val = 0;

	// get the file root
	if (argc < 2) {
		print_opts();
		return 1;
	}
	// set the file name
	file_name = argv[1];

	// open the file
	FILE* vmdk_file = fopen(file_name,"r");
	if (vmdk_file == NULL) {
		printf("# Could not open the file %s\n", file_name);
		ret_val = -1;
		goto end;
	}
	// read the structure
	size_t headers_read = fread(&header_data, sizeof(header_data), 1, vmdk_file);
	// check that we read the header
	if (headers_read != 1) {
		printf("# Failed to read the header for %s\n", file_name);
		ret_val = -1;
		goto close_file;
	}
	// check that the first number is the magic
	if (header_data.magicNumber != SPARSE_MAGICNUMBER) {
		printf("# %s file does not have the correct magic number %x\n", file_name, header_data.magicNumber);
		goto close_file;
	}
	// print the structure
	printf("RW %" PRIu64 " SPARSE \"%s\"\n",header_data.capacity, file_name);

close_file:
	fclose(vmdk_file);
end:
	return ret_val;
}
